export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "error-container": "var(--color-error-container)",
        "surface-hover": "var(--color-surface-hover)",
        tertiary: "var(--color-tertiary)",
        "on-background": "var(--color-on-background)",
        error: "var(--color-error)",
        "tertiary-container": "var(--color-tertiary-container)",
        "primary-fixed": "var(--color-primary-fixed)",
        primary: "var(--color-primary)",
        "secondary-container": "var(--color-secondary-container)",
        "on-primary": "var(--color-on-primary)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-variant": "var(--color-surface-variant)",
        "surface-dim": "var(--color-surface-dim)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "primary-container": "var(--color-primary-container)",
        "inverse-surface": "var(--color-inverse-surface)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "text-primary": "var(--color-text-primary)",
        "on-error-container": "var(--color-on-error-container)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "text-secondary": "var(--color-text-secondary)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        secondary: "var(--color-secondary)",
        "surface-bright": "var(--color-surface-bright)",
        "border-subtle": "var(--color-border-subtle)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-secondary": "var(--color-on-secondary)",
        background: "var(--color-background)",
        "inverse-primary": "var(--color-inverse-primary)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        surface: "var(--color-surface)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "on-surface": "var(--color-on-surface)",
        "on-error": "var(--color-on-error)",
        "outline-variant": "var(--color-outline-variant)",
        "surface-container": "var(--color-surface-container)",
        "surface-card": "var(--color-surface-card)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "background-main": "var(--color-background-main)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "surface-tint": "var(--color-surface-tint)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "surface-container-low": "var(--color-surface-container-low)",
        outline: "var(--color-outline)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "on-primary-container": "var(--color-on-primary-container)",
        "on-tertiary": "var(--color-on-tertiary)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "0.5rem",
        "container-max": "1280px",
        "stack-lg": "2rem",
        "margin-desktop": "2rem",
        "stack-md": "1rem",
        "margin-mobile": "1rem",
        gutter: "1.5rem",
      },
      fontFamily: {
        sans: ["Hanken Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-sm": ["Hanken Grotesk", "sans-serif"],
        "body-sm": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "label-md": ["13px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-lg": [
          "30px",
          { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
};
