export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "secondary-fixed-dim": "#4edea3",
              "surface-container-highest": "#303541",
              "on-tertiary-fixed": "#2a1700",
              "error-container": "#93000a",
              "surface-hover": "#222a3a",
              "tertiary": "#ffb95f",
              "on-background": "#dee2f2",
              "error": "#ffb4ab",
              "tertiary-container": "#ca8100",
              "primary-fixed": "#d8e2ff",
              "primary": "#adc6ff",
              "secondary-container": "#00a572",
              "on-primary": "#002e6a",
              "tertiary-fixed-dim": "#ffb95f",
              "surface-container-high": "#252a35",
              "surface-variant": "#303541",
              "surface-dim": "#0e131e",
              "secondary-fixed": "#6ffbbe",
              "primary-container": "#4d8eff",
              "inverse-surface": "#dee2f2",
              "inverse-on-surface": "#2b303c",
              "text-primary": "#f9fafb",
              "on-error-container": "#ffdad6",
              "on-secondary-fixed-variant": "#005236",
              "text-secondary": "#9ca3af",
              "on-tertiary-fixed-variant": "#653e00",
              "secondary": "#4edea3",
              "surface-bright": "#343945",
              "border-subtle": "#2d3748",
              "surface-container-lowest": "#090e19",
              "on-secondary": "#003824",
              "background": "#0e131e",
              "inverse-primary": "#005ac2",
              "on-primary-fixed": "#001a42",
              "on-surface-variant": "#c2c6d6",
              "primary-fixed-dim": "#adc6ff",
              "surface": "#0e131e",
              "on-primary-fixed-variant": "#004395",
              "on-surface": "#dee2f2",
              "on-error": "#690005",
              "outline-variant": "#424754",
              "surface-container": "#1b202b",
              "surface-card": "#161b26",
              "tertiary-fixed": "#ffddb8",
              "background-main": "#0b0f19",
              "on-tertiary-container": "#3e2400",
              "surface-tint": "#adc6ff",
              "on-secondary-container": "#00311f",
              "surface-container-low": "#171c27",
              "outline": "#8c909f",
              "on-secondary-fixed": "#002113",
              "on-primary-container": "#00285d",
              "on-tertiary": "#472a00"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "stack-sm": "0.5rem",
              "container-max": "1280px",
              "stack-lg": "2rem",
              "margin-desktop": "2rem",
              "stack-md": "1rem",
              "margin-mobile": "1rem",
              "gutter": "1.5rem"
      },
      "fontFamily": {
              "body-md": ["Hanken Grotesk"],
              "label-sm": ["JetBrains Mono"],
              "headline-lg-mobile": ["Hanken Grotesk"],
              "label-md": ["JetBrains Mono"],
              "headline-md": ["Hanken Grotesk"],
              "headline-lg": ["Hanken Grotesk"],
              "headline-sm": ["Hanken Grotesk"],
              "body-sm": ["Hanken Grotesk"],
              "body-lg": ["Hanken Grotesk"]
      },
      "fontSize": {
              "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
              "label-sm": ["11px", {"lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "500"}],
              "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
              "label-md": ["13px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}],
              "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "headline-lg": ["30px", {"lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
              "body-sm": ["12px", {"lineHeight": "18px", "fontWeight": "400"}],
              "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    }
  }
}
